#!/bin/bash

. ~/.config/bspwm/scripts/display.sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x parcellite > /dev/null || parcellite &
xsetroot -cursor_name  left_ptr
xrdb ~/.Xresources
setxkbmap 'us,ru' -option 'grp:caps_toggle'
xset -dpms
xset s off 

if [ $HLEB_DISPLAY_MODE == 'dual' ]; then
  ~/.config/bspwm/scripts/dual_monitors.sh
elif [ $HLEB_DISPLAY_MODE == 'single' ]; then
  ~/.config/bspwm/scripts/single_monitor.sh
fi

~/.config/bspwm/scripts/disable_keyboard.sh

bspc config split_ratio 0.5

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#AE81FF"
bspc config presel_feedback_color "#23252e"

bspc config focus_follows_pointer true
bspc config pointer_modifier	mod4

bspc config borderless_monocle   true
bspc config gapless_monocle      false

# xprop | grep WM_CLASS
bspc rule -a feh state=floating follow=true

# cursor normalize
bspc rule -a Lxappearance follow=false desktop="10"
lxappearance &>/dev/null & pid=$! && sleep 2 && kill -9 $pid 
bspc rule -r Lxappearance

