#! /bin/sh

. ~/.config/scripts/display.sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_prt &
xrdb ~/.Xresources
~/.config/scripts/startdunst.sh &
setxkbmap 'us,ru' -option 'grp:caps_toggle'
pgrep -x parcellite > /dev/null || parcellite &
pgrep -x picom > /dev/null || picom &
xset -dpms
xset s off 

if [ $HLEB_DISPLAY_MODE == 'dual' ]; then
  ~/.config/bspwm/dual_monitors.sh
elif [ $HLEB_DISPLAY_MODE == 'single' ]; then
  ~/.config/bspwm/single_monitor.sh
fi

bspc config split_ratio          0.5

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#AE81FF"
bspc config presel_feedback_color "#23252e"

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

bspc config borderless_monocle   true
bspc config gapless_monocle      false

# xprop | grep WM_CLASS
bspc rule -a feh state=floating follow=true

# cursor normalize
bspc rule -a Lxappearance follow=false desktop="^10"
lxappearance & pid=$! && sleep 2 && kill -9 $pid
bspc rule -r Lxappearance
